CREATE TABLE drivers (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	phone VARCHAR(50) NOT NULL UNIQUE,
	address TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
